---
title: "Project"
author: "Hyun Suk (Max) Ryoo (hr2ee)"
date: "11/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Data Processing
library(tidyverse)
library(dplyr)
setwd("/Users/maxryoo/Documents/MSDS/STAT6021/Project2")
data <- read.csv("data/insurance.csv")
head(data)
```

```{r}
data$significant.charge = as.factor(data$charges > mean(data$charges))
head(data)
```
```{r}
ggplot(aes(x=bmi, y=charges, color=smoker), data=data) + 
  labs(title="Scatter Plot of Charges vs BMI by Smoker Status") +
  theme_bw() +
  geom_point()
```

```{r}
ggplot(aes(x=age,y=charges, color=smoker, size=bmi), data=data) + 
  labs(title="Scatter plot of Charges vs Age by BMI and Smoker Status") +
  theme_bw() +
  geom_point(alpha=0.5)
```

```{r}
ggplot(aes(x=age,y=bmi, color=significant.charge), data=data) + 
  labs(title="Scatter plot of Charges vs Age by BMI and Smoker Status") +
  theme_bw() +
  geom_point(alpha=0.5)

ggplot(data, aes(x=region, y=age, fill=as.factor(significant.charge)))+
  geom_boxplot() +
  theme_bw() +
  labs(x="region", y="ages", title="Dist of bmi by region and smoker status")

ggplot(data, aes(x=smoker, y=bmi, fill=as.factor(significant.charge)))+
  geom_boxplot() +
  theme_bw() +
  labs(x="Region", y="bmi", title="Distribution of bmi by region and smoker status") +  scale_y_continuous(limits=c(10,60), breaks=seq(10,60,5)) 

```





